### PR TITLE
feat: added  optional opentelemetry tracer logging

### LINKED ISSUE #448: Opentelemetry integration
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
Now, suggested tracing solution on gcp for node is to use [opentelemetry ](https://cloud.google.com/trace/docs/setup) but this bunyan logger is integrating only with gcp trace library. 
 **Describe the solution you'd like**
Handle integration with Opentelemetry the same as with gcp trace library

### PR DESCRIPTION
**Pull request by davearata-snorack**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-logging-bunyan/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes [#448](https://github.com/googleapis/nodejs-logging-bunyan/issues/448) 🦕

### CODE REVIEW

**Comment by davearata-snorack** [comment]
> @googlebot I signed it!

**Comment by nicoleczhu** [comment]
@davearata-snorack can you edit your PR title per [conventional commit semantics](https://nitayneeman.com/posts/understanding-semantic-commit-messages-using-git-and-angular/#build)? The reason that's important is that this repo does auto release based on the types of changes committed for release.

**Comment by nicoleczhu** [comment]
@davearata-snorack can you resolve conflicts in package.json? 
Drafting this PR in the meantime

**Comment by nicoleczhu** [comment]
FYI, `traceparent` detection was implemented upstream in nodejs-logging [here](https://github.com/googleapis/nodejs-logging/blob/master/src/context.ts). Closing this PR as it's not needed for now - but feel free to reopen as the upstream impl was low level and we can always add additional otel support within this library.

**Pull request closed without merging**
