### PR TITLE
fix: update HttpRequest to match @google-cloud/logging

### LINKED ISSUE #413: HTTPRequest types are invalid
Currently, emitting a log containing an httpRequest that is strongly typed using types.HttpRequest can result in a couple of errors:

* "Empty string" when sending a field for which we don't have information.
* google.logging.type.HttpRequest.latency: object expected

Ideally, these types would match those defined in @google-cloud/logging

## Environment details

  - `@google-cloud/logging-bunyan` version: 2.0.3

### PR DESCRIPTION
**Pull request by majelbstoat**
This PR changes the definition of types.HttpRequest to match that defined in https://github.com/googleapis/nodejs-logging/blob/master/src/http-request.ts. In particular, it makes all fields optional, changes latency to the format that matches the underlying proto, and changes a couple of string fields to numbers.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-logging-bunyan/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #413 🦕

### CODE REVIEW

**Comment by majelbstoat** [comment]
@googlebot I signed it!

**Comment by bcoe** [comment]
@majelbstoat just wanted to put this back on your radar, what do you think of my comment.

**Comment by majelbstoat** [comment]
Oh, hi! I assumed you were waiting on an answer from @soldair, sorry. But I guess, whatever the reasons it was supported, this would be a breaking change, yes, if people were relying on it, and your suggestion to make the type `string | {seconds: number; nanos: number}`  would be a reasonable stop-gap.

**Comment by bcoe** [comment]
@majelbstoat thank you for the contribution, this will be released soon.

**Pull request merged**
