### PR TITLE
chore: fix install tests

### PR DESCRIPTION
**Pull request by DominicKramer**
Fixes: #132

### CODE REVIEW

**Comment by ofrobots** [comment]
@crwilcox @JustinBeckwith any idea what is going on with the kokoro tests? When did they show up, where is the config and how can this PR be landed given that they are failing?

**Comment by DominicKramer** [comment]
@JustinBeckwith this PR should unblock our ability to make a new release from a system tests failure perspective.  However, I don't think a release can happen because of the Kokoro test failures that look like a test configuration failure.  Do you have a fix for the Kokoro failures or can you disable them until they are more stable?  Thanks

**Comment by ofrobots** [comment]
As per @JustinBeckwith over chat: 'you can safely ignore them.'.

**Comment by ofrobots** [comment]
Once the merge-CI is green for this commit (https://circleci.com/workflow-run/7e21c010-3035-4b13-970f-c6be06aa804d), it would be good to do a 0.9.1 release. 0.9.0 never got out of the door.

**Pull request merged**
