### PR TITLE
fix: skip parent request entry on cloud run

### LINKED ISSUE #626: Duplicate http request entries when running in Cloud Run
Hi,

My application is deployed as a container on Cloud Run, and I was observing duplicate request entries in the logs explorer:

Screen Shot 2022-05-09 at 07 40 20

Digging in the code, I found out that the library omits the duplicate logs when running in app engine and cloud functions, so I forked the library and added the case for cloud run, and it fixed my issue:

https://github.com/valian-ca/nodejs-logging-bunyan/commit/0a175adc55c0efb774424f6e671fec91243e0b05

Would this be the correct fix for this?

Thanks!

### PR DESCRIPTION
**Pull request by wvanderdeijl**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-logging-bunyan/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #626

We also suffer from this issue. As a (dirty) workaround we have no added the following code to our own codebase:
```
// workaround for https://github.com/googleapis/nodejs-logging-bunyan/issues/626 to let lib know we are running in GCP
if (process.env.K_SERVICE && !process.env.GAE_SERVICE) {
    // trick library into thinking we run on AppEngine
    process.env.GAE_SERVICE = process.env.K_SERVICE;
}
```

### CODE REVIEW

**Review by losalex — COMMENTED** [review]
Thanks @wvanderdeijl for making this change! Overall the change looks good. I wonder if you can also cover this behavior in system-test like one we have in: https://github.com/googleapis/nodejs-logging-bunyan/blob/f3ed3aa973d0e2cd1f7311ef48a69cbd72df80f1/test/middleware/test-express.ts#L128

**Comment by wvanderdeijl** [comment]
What other test scenario would you like to see there?

I already added a separate test to that file for the situation on Cloud Run with the new option set to true. I decided not to include it in the current test with the forEach over GCF/GAE as I didn't want to set the option for those two as well.

**Comment by losalex** [comment]
> nodejs-logging-bunyan/test/middleware/test-express.ts

I believe we should make sure that for `GCPEnv.CLOUD_RUN`  the behavior is correct when `skipParentEntryForCloudRun` is set  to `true`

**Comment by wvanderdeijl** [comment]
@losalex isnt’t that the test I added to `nodejs-logging-bunyan/test/middleware/test-express.ts`? Or are you looking for something else?

**Comment by losalex** [comment]
> @losalex isnt’t that the test I added to `nodejs-logging-bunyan/test/middleware/test-express.ts`? Or are you looking for something else?

@wvanderdeijl , my bad, it seems I might confuse you - would you be able to merge your new test with one I provided? This way we can keep them all together to make sure it will prevent any confusion in the future.

**Review by losalex — APPROVED** [review]
LGTM

**Pull request merged**
