### PR TITLE
chore(deps): update dependency cpy-cli to v4

### PR DESCRIPTION
**Pull request by sofisl**

### CODE REVIEW

**Review by losalex — COMMENTED** [review]
System test still fails with "error TS2307: Cannot find module './types/core' or its corresponding type declarations.". I wonder if we really need to update `cp-cli` - it seems that this change requires extra dependency, correct?

**Review by losalex — COMMENTED** [review]
This still fails...

**Comment by sofisl** [comment]
@losalex, this is an attempt at updating this dependency: https://github.com/googleapis/nodejs-logging-bunyan/pull/598

I'm not sure how to fix it, it seems like this ugprade is buggy: https://github.com/sindresorhus/cpy-cli/issues/35 (there are more as well). I haven't had the chance to come back and look at this yet, if you do have cycles to upgrade it correctly I'd greatly appreciate it!

**Review by losalex — APPROVED** [review]
Thanks for fixing this - much appreciated!

**Pull request merged**
